### ISSUE TITLE
Incorrect Mutex Example

### ISSUE THREAD

**Issue by pca006132** [stjepang/event-listener#10]
https://github.com/stjepang/event-listener/blob/fe9ec7e60e94d3f5b96f0cf54cbb57cc34118868/examples/mutex.rs#L42-L48

Swap would return the previous value, so line 43 should be changed or the two values in line 44 and 46 should be swapped.

**Comment by stjepang** [comment]
Good catch, thanks! :)

**Comment by stjepang** [comment]
Fixed.
