### ISSUE TITLE
Incorrect mutex example

### ISSUE THREAD

**Issue by songzhi** [stjepang/event-listener#16]
The `mutex` example compiles but run incorrectly in my computer. I did some fixup and it works.

```rust
impl<T> Drop for MutexGuard<'_, T> {
    fn drop(&mut self) {
        self.0.locked.store(false, Ordering::Release);
        self.0.lock_ops.notify(1);
    }
}
```

**Comment by stjepang** [comment]
You're right :) I have added the `Drop` impl for `MutexGuard` to the example. Thanks!
