### ISSUE TITLE
Notifying additional listeners

### ISSUE THREAD

**Issue by withoutboats** [stjepang/event-listener#3]
I'm pretty sure my use case for `Event::notify` wants to notify `n` *additional* listeners. You can see the code here: https://github.com/withoutboats/access-queue/blob/master/src/lib.rs

It's like a generalization of a Mutex which rather than using an `AtomicBool`, allows up to `count` concurrent accesses, used by a counter which decrements toward zero as accesses are given out, and increments back up as they are released. Whenever accesses are released, I want to increase the number of notified listeners until I hit the number of active listeners.

My understanding of the code is that if accesses are released before all of the previously notified listeners have awoken, some listeners can end up dropped, as they are not notified, but there is now free space in the queue which new attempts to access will take.

Is it possible to provide a version of `Event::notify` which will notify additional active listeners (up to the number of active listeners in total)?

**Comment by stjepang** [comment]
Done - I have just added `Event::notify_additional()` in v1.2.0
