### ISSUE TITLE
poll not waking when Pending is returned

### ISSUE THREAD

**Issue by Licenser** [stjepang/event-listener#7]
This is a follow up to https://github.com/async-rs/async-std/issues/841 I tracked the poll that isn't waking in the chain down to the EventListener.

It seems that when pending is returned 

```
cx.waker().wake_by_ref();
```

needs to be called or having more event listeners active then executer threads seems to lead to them indefinitively spinning.

I'll add a PR for this.

**Comment by stjepang** [comment]
What's the status here? Thoughts on this comment? https://github.com/async-rs/async-std/issues/834#issuecomment-663507266

My understanding is that this is not a bug, but I could be misunderstanding.

**Comment by Licenser** [comment]
The two things are independent of each other. The problem here, from what I understood, is that if there are enough event-listeners they could block the entire pool since they'll never wake another task when they're pending.

**Comment by stjepang** [comment]
Hmm I'm a bit confused by that PR. An `EventListener` is notified from `notify()` by waking the waker stored in its state.

If an `EventListener` is polled and hasn't been notified yet, we need to return `Pending`. I don't understand why we would wake the waker at that point. Won't that reschedule the same task that will likely just poll `EventListener` again and keep doing that forever?

**Comment by Licenser** [comment]
Hmm, that makes sense, I understood the docs for the weaker differently - I thought it would need to be called to **not** reschedule the same task :); yes then this makes no sense at all.
